<?php 
/*****************************************
File: configEdit.phtml
Creator: Kyle Conrad
Created: July 13/2018
Program that lets user edit the contents of a particular property from the property table of db
******************************************/
?>

<h1>Edit Property Value</h1>
<form method='GET'>
	<h2>Editing <?php echo $prop->getKey() ?></h2>

	<textarea rows='10' cols='120'>
		<?php echo htmlentities($prop->getValue(), ENT_QUOTES) ?>	
	</textarea>
</form>
