<?php 
/*****************************************
File: index.phtml
Creator: Derek Dekroon
Created: December 23/2018
Registration control panel
******************************************/
?>

<h1>
	Registration Control Panel
	<span class="f-small"><?php echo isset($curLeague) && $curLeague->getId() != null ? ' - ' . $curLeague->getFormattedName() : "" ?></span>
	<div class="float-right">
		<a class="btn-title-link" target="_blank" title="Print Individual Teams" href="<?php echo $router->pathFor('cp-print-individuals-teams', ['leagueID' => $curLeague->getId()]) ?>">
			<span class="glyphicon glyphicon-print"></span>
		</a>
		<a class="btn-title-link" target="_blank" title="excel code" href="<?php echo $router->pathFor('cp-league-excel-code', ['leagueID' => $curLeague->getId()]) ?>">
			<span class="glyphicon glyphicon-th"></span>
		</a>
	</div>
</h1>

<?php 
	print $this->fetch('control-panel/league-selector.phtml', [
		"router" => $router,
		"request" => $request,
		"baseUrlName" => 'cp-registration',
		"sports" => $allSports,
		"seasons" => $seasons,
		"activeSport" => $curSport,
		"activeLeague" => $curLeague,
		"includeSeasons" => false,
		"showFullLabels" => true
	]);
?>

<div class="form-group row no-flex">
	<div class="col-xs-6">
		<h3 class="clearfix">
			Teams
			<button class="btn btn-primary btn-xs float-right" onClick="quickAddTeam(<?php echo $curLeague->getId() ?>)">
				<span class="glyphicon glyphicon-plus-sign"></span> Quick add
			</button>
		</h3>
		<table id="RegistrationLeagueTeamsTable" class="table table-sortable">			
			<tbody>
				<?php foreach($curLeague->getTeams() as $curTeam) { ?>
					<tr class="droppable team" data-team-id="<?php echo $curTeam->getId() ?>">
						<td><span class="glyphicon glyphicon-menu-hamburger"></span></td>
						<td>
							<?php print $curTeam->getNumInLeague() ?>
						</td><td>
							<a <?php echo $curTeam->getTeamHasIndividuals() ? "style='font-weight:700;'" : '' ?>
								href='<?php echo $router->pathFor('cp-edit-team', ['sportID' => $curSport->getId(), 'leagueID' => $curLeague->getId(),  'teamID' => $curTeam->getId()]) ?>'>
								<?php echo $curTeam->getName() ?></a> 
							<small>
								<?php echo $curTeam->getIsDroppedOut() ? ' - Dropout' : '' ?>
								<?php echo $curTeam->getIsConvenor() ? ' - Convenor' : '' ?>
							</small>
						</td><td>
							<div class="float-right btn-group">
								<button class="btn btn-default btn-xs<?php echo $curTeam->getIsPaid() ? ' active' : '' ?>" onClick="togglePaid(this, <?php echo $curTeam->getId() ?>);">
									<span class="glyphicon glyphicon-piggy-bank"></span>
								</button>
								<button class="btn btn-default btn-xs" onClick="deregisterTeam(this, <?php echo $curTeam->getId() ?>, function() { location.reload(); });">
									<span class="glyphicon glyphicon-remove"></span>
								</button>
							</div>
						</td>
					</tr>
				<?php } ?>
			</tbody>
		</table>
	</div>
	<div class="col-xs-6">
		<h3>Free Agents</h3>
		<?php 
			print $this->fetch('control-panel/registration/components/freeAgents.phtml', [
				"router" => $router,
				"request" => $request,
				"league" => $curLeague
			]); 
		?>
	</div>
</div>

<div class="teamsOnTheFence">
	<h3>Teams on the Fence</h3>
	
	<?php if(sizeof($curLeague->getFenceTeams()) > 0) { ?>
		<table class='table'>
			<thead>
				<tr>
					<td></td>
					<td>Name</td>
					<td>Captain</td>
					<td>Email</td>
					<td></td>
				</tr>
			</thead>
			<tbody>
				<?php $fenceTeamsCounter = 1; ?>
				<?php foreach($curLeague->getFenceTeams() as $curFenceTeam) { ?>
					<tr class="team">
						<td>
							<?php echo $fenceTeamsCounter++; ?>
						</td><td>
							<a href="<?php echo $router->pathFor('cp-edit-team', ['sportID' => $curSport->getId(), 'leagueID' => $curLeague->getId(), 'teamID' => $curFenceTeam->getId() ]) ?>">
								<?php echo $curFenceTeam->getName() ?>
							</a>
						</td><td>
							<?php echo $curFenceTeam->getCaptain()->getFirstName() . ' ' . $curFenceTeam->getCaptain()->getLastName() ?>
						</td><td>
							<?php print "<a target='_blank' href='mailto:" . $curFenceTeam->getCaptain()->getEmail() . "'>" . $curFenceTeam->getCaptain()->getEmail() . '</a>'; ?>
						</td><td>
							<div class="float-right btn-group">
								<button class='btn btn-default btn-xs' onClick='registerTeam(this, <?php echo $curFenceTeam->getId() ?>, function() { location.reload(); })'><span class='glyphicon glyphicon-plus-sign'></span> Register</span></button>
								<button class='btn btn-default btn-xs' onClick='deleteTeam(this, <?php echo $curFenceTeam->getId() ?>)'><span class='glyphicon glyphicon-trash'></span> Delete</span></button>
							</div>
						</td>
					</tr>
				<?php } ?>
			</tbody>
		</table>
	<?php } else { ?>
		<p>No teams to show</p>
	<?php } ?> 			
</div>

<script>
	$(function() {
		$("#RegistrationLeagueTeams").sortable();

		$(".draggable").draggable({ 
			revert: true,
			handle: ".handle",
			zIndex: 1000,
			start: function(event, ui) {
				$(".droppable").addClass("dragging");
			},
			stop: function(event, ui) {
				$(".droppable").removeClass("dragging");
			}
		});

		$(".droppable").droppable({
			drop: function(event, ui) {
				var fa = $(ui.draggable);
				var team = $(this);
				var playerId = fa.data("player-id");
				var groupId = fa.data("group-id");
				var teamId = team.data("team-id");

				var successCallback = function() {
					ui.draggable.remove();
					team.find("a").css("font-weight", 700);
				}

				if(groupId > 0) {
					addGroupToTeam(groupId, teamId, successCallback);
				} else {
					addPlayerToTeam(playerId, teamId, successCallback);
				}
			},
			over: function(event, ui) {
				$(this).addClass("over");
			},
			out: function(event, ui) {
				$(this).removeClass("over");
			}
		});
	});

	
</script>