<div id='ScoreReporterThankYou'>
	<div class='container-fluid text-center'>
		<h2>Thank you for submitting your team's score</h2>
		<br />
		<h4>Good luck with your games next week!</h4>
		<p>&nbsp;</p>
		<p class="image"><img border="0" src="/Logos/Perpetualmotionlogo2.jpg" width="95%" style="max-width:400px;"></p>
		<p>&nbsp;</p>
		<div class='row'>
			<div class='col-sm-4 col-xs-12'>
				<a class='px-2' target='_top' href='http://perpetualmotion.org/<?php echo $sport->getBaseUrl() ?>/<?php echo $sport->getBaseUrl() ?>-schedule?leagueID=<?php echo $league->getId() ?>'>
					<?php print $league->getName() . ' Schedule' ?>
				</a>
			</div>
			<div class='col-sm-4 col-xs-12'>
				<a class='px-2' target='_top' href='http://perpetualmotion.org/<?php echo $sport->getBaseUrl() ?>/<?php echo $sport->getBaseUrl() ?>-standings?leagueID=<?php echo $league->getId() ?>'>
					<?php print $league->getName() . ' Standings' ?>
				</a>
			</div>
			<div class='col-sm-4 col-xs-12'>
				<a class='px-2' target='_top' href='http://perpetualmotion.org/<?php echo $sport->getBaseUrl() ?>/teamPage?teamID=<?php echo $team->getId() ?>'>
					<?php print $team->getName() . ' Team Page' ?>
				</a>
			</div>
		</div>
	</div>
</div>