
<link href="/css/stylesheets/jquery-ui.min.css" rel="stylesheet" type="text/css" />
<link href="/css/stylesheets/bootstrap-slider.min.css" rel="stylesheet" type="text/css" />
<link href="/css/stylesheets/styles.css" rel="stylesheet" type="text/css" />

<form class='scoreReporter scoreReporter-<?php print $sport->getId() ?> container-fluid' id="ScoreReporterForm">
	<input type="hidden" name="sportID" value='<?php print $sport->getId() ?>' />
	<div class='clearfix form-group'>
		<div class="logoContainer pull-right" style="text-align:center;">
			<img src="<?php print $sport->getLogoLink(); ?>" alt="" />
		</div>
		<h1>Score Reporter</h1>
	</div>
	
	<fieldset class='form-group'>
		<legend>Game Information</legend>
		<div class='form-group row'>
			<div class='col-md-2 col-sm-3 col-xs-4'>
				<label for='SelectLeague'>Select League</label>
			</div>
			<div class='col-md-10 col-sm-9 col-xs-8'>
				<select id='SelectLeague' name='leagueID' class='form-control'>
					<option value='-1'></option>
					<?php if(count($leagues) > 0) { ?>
						<optgroup label='<?php echo $leagues[0]->getSeason()->getName() ?>'>
							<?php 
								$lastSeasonId = 0;
								foreach($leagues as $curLeague) {

									if($curLeague->getSeasonId() != $lastSeasonId && $lastSeasonId != 0) {
										print '</optgroup><optgroup label="' . $league->getSeason()->getName() . '">';
									}

									print "<option value='" . $curLeague->getId() . "' " 
											. ($curLeague->getId() == $league->getId() ? "selected='selected'" : '') . ">"
											. $curLeague->getName() . " - " . $curLeague->getDayString()
											. "</option>";

									$lastSeasonId = $curLeague->getSeasonId();
								}
							?>
						</optgroup>
					<?php } ?>
				</select>
			</div>
		</div>
		<div class='form-group row'>
			<div class='col-md-2 col-sm-3 col-xs-4'>
				<label for='SelectTeam'>Select Team</label>
			</div>
			<div class='col-md-10 col-sm-9 col-xs-8'>
				<select id='SelectTeam' name='teamID' class='form-control'>
					<option value='-1'></option>
				</select>
			</div>
		</div>

		<div class="weekDate"></div>
	</fieldset>
	<fieldset id='MatchesFieldset' style='display:none;' class='form-group'>
		<legend>Matches</legend>
		<div id="Matches">

		</div>
	</fieldset>
	<fieldset id='ContactFieldset' class='form-group'>
		<legend>Contact Information</legend>
		<div class='row form-group'>
			<div class='col-md-2 col-sm-3 col-xs-4'>
				<label for='SubmitterName'>Name <span class="required">*</span></label>
			</div>
			<div class='col-md-10 col-sm-9 col-xs-8'>
				<div class="input-group">
					<span class="input-group-addon" id="SubmitUsernameAddon"><span class="glyphicon glyphicon-user" aria-hidden="true"></span></span>
					<input type='text' id='SubmitterName' name='submitterName' value='<?php echo isset($user) && $user != null ? $user->getFirstName() . " " . $user->getLastName() : "" ?>' class='form-control' aria-describedby='SubmitUsernameAddon' />
				</div>
			</div>
		</div>
		<div class='row form-group'>
			<div class='col-md-2 col-sm-3 col-xs-4'>
				<label for='SubmitterEmail'>Email</label>
			</div>
			<div class='col-md-10 col-sm-9 col-xs-8'>
				<div class="input-group">
					<span class="input-group-addon" id="SubmitEmailAddon">@</span>
					<input type='email' id='SubmitterEmail' name='submitterEmail' value='<?php echo isset($user) && $user != null ? $user->getEmail() : "" ?>' class='form-control' aria-describedby="SubmitEmailAddon" />
				</div>
			</div>
		</div>
		<div class="form-group">
			<button type='submit' value='submitScore' name='action' class='btn btn-primary'>Submit</button>
		</div>
	</fieldset>
</form>

<script>	
	$(function() {
		
		$("#SelectLeague").change(function() {
			getLeagueTeams($("#SelectTeam"), $(this).val(), 0);
		});
		
		$("#SelectTeam").change(function() {
			loadMatches($(this).val());
		});
		
		<?php if($league != null && $league->getId() != null) { ?> 
			getLeagueTeams($("#SelectTeam"), <?php print $league->getId() ?>, <?php print $team != null && $team->getId() != null ? $team->getId() : 0 ?>); 
		<?php } ?>
		<?php if($team != null && $team->getId() != null) { ?> 
			loadMatches(<?php print $team->getId() ?>);
		<?php } ?>
		
		$("#ScoreReporterForm").ajaxForm({
			method:"post",
			type:"post",
			url:"<?php echo (isset($isDashboard) && $isDashboard ? $router->pathFor('dashboard-report-score') : $router->pathFor('report-score')); ?>",
			dataType:"json",
			success:function(resp) {
				if(resp.status == 1) {
					var cont = $("<div />").html(resp.html);
					$("#ScoreReporterForm").replaceWith(cont);
				} else {
					alert(resp.errorMessage);
				}
			},
			error:function() {
				alert("Error connecting to the server. Please try again.");
			}
		});
	});
	
	function getLeagueTeams(select, leagueId, selectedTeamId) {
		if(leagueId > 0) {
			$.ajax({
				url:"/Derek/get-league-teams/" + leagueId,
				dataType:"json",
				success: function(resp) {
					if(resp.status === 1 && resp.data.hasOwnProperty('teams')) {
						select.html("<option value='-1'></option>");
						for(var i in resp.data.teams) {
							var team = resp.data.teams[i];
							var id = team.id;
							var name = team.name;
							
							select.append("<option value='" + id + "' " + (selectedTeamId == id ? "selected='selected'" : "") + ">" + name + "</option>");
						}
					} else {
						alert(resp.errorMessage);
					}
				},
				error: function() {
					alert("Error connecting to server.");
				}
			});
		}
	}
	
	function loadMatches(teamId) {
		if(teamId > 0) {
			
			var loadData = function() {
				$("#Matches .game").each(function() {
					var oppTeamId = $(this).attr("data-opp-team-id");
					getLeagueTeams($(this).find(".teamSelect"), $("#SelectLeague").val(), oppTeamId);
				});

				$("#Matches").find(".radioButtons").bsFormButtonset('attach');
				$("#Matches").find("input[type='number']").spinner();

				$("#Matches").find(".spirit").each(function() {
					$(this).bootstrapSlider({
						precision:1,
						step: 0.5,
						min: 1,
						max: 5,
						value:5,
						ticks: [1, 2, 3, 4, 5],
						ticks_labels: ['1', '2', '3', '4', '5']
					});

					/* $(this).on("change", function(slideEvt) {
						$("#" + $(slideEvt.target).attr("id") + "_Val").text(slideEvt.value.newValue);
					}); */
				});

				$("#Matches").find("> .row").animate({opacity:1}, 200);
			};
			
			
			$.ajax({
				url:"/Derek/score-reporter-matches/" + teamId,
				dataType:"html",
				success: function(resp) {
					
					if($("#Matches").find("> .row").length > 0) {
						$("#Matches").find("> .row").animate({opacity:0}, 200, function() {
							$("#Matches").html(resp);
							loadData();
						});
					} else {
						$("#Matches").html(resp);
						$("#MatchesFieldset").slideDown(300, function() {
							loadData();
						});
					}
				},
				error: function() {
					alert("Error connecting to server.");
				}
			});
		} else {
			$("#MatchesFieldset").slideUp();
		}
	}
</script>