
<link href="/css/stylesheets/jquery-ui.min.css" rel="stylesheet" type="text/css" />
<link href="/css/stylesheets/bootstrap-slider.min.css" rel="stylesheet" type="text/css" />
<link href="/css/stylesheets/styles.css" rel="stylesheet" type="text/css" />

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src='/js/bootstrap-form-buttonset.js'></script>
<script src='/js/bootstrap-slider.min.js'></script>

<script src="/js/jquery-ui.min.js"></script>

<script>	
	$(function() {
		
		$("#SelectLeague").change(function() {
			getLeagueTeams($("#SelectTeam"), $(this).val(), 0);
		});
		
		$("#SelectTeam").change(function() {
			loadMatches($(this).val());
		});
		
		getLeagueTeams($("#SelectTeam"), <?php print $leagueID ?>, <?php print $teamID ?>);
		loadMatches(<?php print $teamID ?>);
	});
	
	function getLeagueTeams(select, leagueId, selectedTeamId) {
		if(leagueId > 0) {
			$.ajax({
				url:"/Derek/get-league-teams/" + leagueId,
				dataType:"json",
				success: function(resp) {
					if(resp.status === 1 && resp.data.hasOwnProperty('teams')) {
						select.html("<option value='-1'></option>");
						for(var i in resp.data.teams) {
							var team = resp.data.teams[i];
							var id = team.id;
							var name = team.name;
							
							select.append("<option value='" + id + "' " + (selectedTeamId == id ? "selected='selected'" : "") + ">" + name + "</option>");
						}
					} else {
						alert(resp.errorMessage);
					}
				},
				error: function() {
					alert("Error connecting to server.");
				}
			});
		}
	}
	
	function loadMatches(teamId) {
		if(teamId > 0) {
			
			var loadData = function() {
				$("#Matches .game").each(function() {
					var oppTeamId = $(this).attr("data-opp-team-id");
					getLeagueTeams($(this).find(".teamSelect"), $("#SelectLeague").val(), oppTeamId);
				});

				$("#Matches").find(".radioButtons").bsFormButtonset('attach');
				$("#Matches").find("input[type='number']").spinner();

				$("#Matches").find(".spirit").each(function() {
					$(this).bootstrapSlider({
						precision:1,
						step: 0.5,
						min: 1,
						max: 5,
						value:5,
						ticks: [1, 2, 3, 4, 5],
						ticks_labels: ['1', '2', '3', '4', '5']
					});

					/* $(this).on("change", function(slideEvt) {
						$("#" + $(slideEvt.target).attr("id") + "_Val").text(slideEvt.value.newValue);
					}); */
				});

				$("#Matches").find("> .row").animate({opacity:1}, 200);
			};
			
			
			$.ajax({
				url:"/Derek/score-reporter-matches/" + teamId,
				dataType:"html",
				success: function(resp) {
					
					if($("#Matches").find("> .row").length > 0) {
						$("#Matches").find("> .row").animate({opacity:0}, 200, function() {
							$("#Matches").html(resp);
							loadData();
						});
					} else {
						$("#Matches").html(resp);
						$("#MatchesFieldset").slideDown(300, function() {
							loadData();
						});
					}
				},
				error: function() {
					alert("Error connecting to server.");
				}
			});
		} else {
			$("#MatchesFieldset").slideUp();
		}
	}
</script>

<div class='scoreReporter scoreReporter-<?php print $sportID ?> container-fluid'>
	<div class='clearfix form-group'>
		<div class="logoContainer pull-right" style="text-align:center;">
			<img src="<?php print $logo; ?>" alt="" />
		</div>
		<h1>Score Reporter</h1>
	</div>
	
	<fieldset class='form-group'>
		<legend>Game Information</legend>
		<div class='form-group row'>
			<div class='col-md-2 col-sm-3 col-xs-4'>
				<label for='SelectLeague'>Select League</label>
			</div>
			<div class='col-md-10 col-sm-9 col-xs-8'>
				<select id='SelectLeague' name='leagueID' class='form-control'>
					<option value='-1'></option>
					<?php 
						$lastSeasonId = 0;
						foreach($leagues as $league) {

							if($league->getSeasonId() != $lastSeasonId && $lastSeasonId != 0) {
								print '<option value="0">-------- ' . $league->getSeasonName() . ' ------</option>';
							}

							print "<option value='" . $league->getId() . "' " 
									. ($league->getId() == $leagueID ? "selected='selected'" : '') . ">"
									. $league->getName() . " - " . $league->getDayString()
									. "</option>";

							$lastSeasonId = $league->getSeasonId();
						}
					?>
				</select>
			</div>
		</div>
		<div class='form-group row'>
			<div class='col-md-2 col-sm-3 col-xs-4'>
				<label for='SelectTeam'>Select Team</label>
			</div>
			<div class='col-md-10 col-sm-9 col-xs-8'>
				<select id='SelectTeam' name='teamID' class='form-control'>
					<option value='-1'></option>
				</select>
			</div>
		</div>

		<div class="weekDate"></div>
	</fieldset>
	<fieldset id='MatchesFieldset' style='display:none;' class='form-group'>
		<legend>Matches</legend>
		<div id="Matches">

		</div>
	</fieldset>
	<fieldset id='ContactFieldset' class='form-group'>
		<legend>Contact Information</legend>
		<div class='row form-group'>
			<div class='col-md-2 col-sm-3 col-xs-4'>
				<label for='SubmitterName'>Name <span class="required">*</span></label>
			</div>
			<div class='col-md-10 col-sm-9 col-xs-8'>
				<div class="input-group">
					<span class="input-group-addon" id="SubmitUsernameAddon"><span class="glyphicon glyphicon-user" aria-hidden="true"></span></span>
					<input type='text' id='SubmitterName' name='submitterName' value='' class='form-control' aria-describedby='SubmitUsernameAddon' />
				</div>
			</div>
		</div>
		<div class='row form-group'>
			<div class='col-md-2 col-sm-3 col-xs-4'>
				<label for='SubmitterEmail'>Email</label>
			</div>
			<div class='col-md-10 col-sm-9 col-xs-8'>
				<div class="input-group">
					<span class="input-group-addon" id="SubmitEmailAddon">@</span>
					<input type='email' id='SubmitterEmail' name='submitemail' value='' class='form-control' aria-describedby="SubmitEmailAddon" />
				</div>
			</div>
		</div>
		<div class="form-group">
			<button type='submit' value='submitScore' name='action' class='btn btn-primary'>Submit</button>
		</div>
	</fieldset>
</div>