
	<link href="/css/stylesheets/jquery-ui.min.css" rel="stylesheet" type="text/css" />
	<link href="/css/stylesheets/styles.css" rel="stylesheet" type="text/css" />
	
	<h1><?php print $team->getName() ?> - <?php print $team->getLeague()->getName() ?> - <?php print $team->getLeague()->getDayString() ?></h2>
	<p class='teamStandings f-large'><?php print $team->getFormattedStandings(); ?></p>

	<div class="matchInfo" align="center">
		<?php $rowNum = 0; ?>
		<table class="table table-condensed table-striped table-responsive f-small">
			<thead>
				<tr>
					<th></th>
					<th>Date</th>
					<th>Opponent</th>
					<th>Result</th>
					<th>Field</th>
					<th>Game Time</th>
					<?php if($team->getLeague()->getSportId() != 2) { ?>
						<th>Colour</th>
					<?php } ?>
				</tr>
			</thead>
			<tbody>
				<?php if($team->getScheduledMatches() != null) { ?>
					<?php $matchCount = 0; ?>
					<?php $lastTeamId = 0; ?>
					<?php foreach($team->getScheduledMatches() as $scheduledMatch) { ?>
						<?php $teamScoreSubmissions = $scheduledMatch->getScoreSubmissions($team); ?>
						<tr>
							<td><?php print ++$matchCount ?></td>
							<td><?php print $scheduledMatch->getFormattedDatePlayed(); ?></td>
							<td>
								<?php if(($teamScoreSubmissions != null && sizeof($teamScoreSubmissions) > 0)) { ?>
									<?php foreach($teamScoreSubmissions as $scoreSubmission) { ?>
										<?php if($scoreSubmission->getOppTeam()->getId() != $lastTeamId) { ?>
											<?php $lastTeamId = $scoreSubmission->getOppTeam()->getId(); ?>
								
											<?php if ($scoreSubmission->getOppTeam()->getId() != 1 && !$scoreSubmission->getOppTeam()->getIsDroppedOut()) { ?>
												<?php $teamPageUrl = $isDashboard ? $router->pathFor('dashboard-team-page', ['teamID' => $scoreSubmission->getOppTeam()->getId()] ) : "" ?>
												<a href='<?php echo $teamPageUrl ?>'><?php print $scoreSubmission->getOppTeam()->getName() ?></a>
												<?php print $scoreSubmission->getOppTeam()->getFormattedStandings(); ?>
											<?php } else { ?>
												<?php print $scoreSubmission->getOppTeam()->getName(); ?>
											<?php } ?>
												
											<?php break; ?>
										<?php } ?>
									<?php } ?>
								<?php } else { ?>
									<?php if ($scheduledMatch->getOppTeam($team)->getId() != 1 && !$scheduledMatch->getOppTeam($team)->getIsDroppedOut()) { ?>
										<?php $teamPageUrl = $isDashboard ? $router->pathFor('dashboard-team-page', ['teamID' => $scheduledMatch->getOppTeam($team)->getId()] ) : "" ?>
										<a href='<?php echo $teamPageUrl ?>'><?php print $scheduledMatch->getOppTeam($team)->getName() ?></a>
										<?php print $scheduledMatch->getOppTeam($team)->getFormattedStandings(); ?>
									<?php } else { ?>
										<?php print $scheduledMatch->getOppTeam($team)->getName(); ?>
									<?php } ?>
								<?php } ?>
							</td>
							<td>
								<?php if($teamScoreSubmissions != null && sizeof($teamScoreSubmissions) > 0) {
									$first = true;
									foreach($teamScoreSubmissions as $scoreSubmission) {
										if($scoreSubmission->getOppTeam()->getId() == $lastTeamId) {
											print (!$first ? ", " : "") . $scoreSubmission->getResultsString();
											$first = false;
										}
									}
								} ?>
							</td>
							<td>
								<a target='_blank' href='http://www.perpetualmotion.org<?php echo $scheduledMatch->getVenue()->getLink() ?>'>
									<?php echo $scheduledMatch->getVenue()->getShortShowName() ?>
								</a>
							</td>
							<td><?php print $scheduledMatch->getFormattedGameTime() ?></td>
							<?php if($team->getLeague()->getSportId() != 2) { ?>
								<td id='shirtColour'><?php echo $scheduledMatch->getTeamOneId() == $team->getId() ? "Dark" : "Light" ?></td>
							<?php } ?>
						</tr>
					<?php } ?>
				<?php } ?>
			</tbody>
		</table>
	</div>

	<p>&nbsp;</p>
	<p><?php print $team->getPic() ?></p>
	<?php if($team->getIsPic()) { ?>
	
		<div class='centerImg' align="center" style="width:90%; max-width:550px;height:auto;">
			<img src="<?php print $team->getPic() ?>" style="width:90%; max-width:550px;height:auto;" />
		</div>
		<p>&nbsp;</p>
		
	<?php } ?>
	
	<?php /* <?php $teams = $team->getLeague()->getTeams(); ?>
		
	<?php if (!$team->getLeague()->getIsSortByWinPct()) { ?>
		<?php usort($teams, array("Controllers_TeamsController", "comparePoints")); ?>
	<?php } else { ?>
		<?php usort($teamObjs, array("Controllers_TeamsController", "comparePercent")); ?>
	<?php } ?> */ ?>
		
	<?php print $this->fetch('standings.phtml', [
		"router" => $router,
		"request" => $request,
		"user" => $user,
		"league" => $team->getLeague(),
		"leagueController" => $leagueController,
		"teamController" => $teamController,
		"includedInTeamPage" => true
	]); ?>
