
<?php 
	if(isset($validationKey) && isset($isKeyValid) && $isKeyValid) {
		$action = $router->pathFor("submit-reset-password", [ "validationKey" => $validationKey ] );
	} else {
		$action = $router->pathFor("request-reset-password", [] );
	} 
?>
	<div class='clearfix form-group'>
		<div class="float-right">
			<img src="/Logos/Perpetualmotionlogo2.jpg" width="300" />
		</div>
		<h1>Reset an Account Password</h1>
	</div>
	<form id="ResetPasswordForm" action="<?php echo $action ?>" method="post">

		<?php if(isset($validationKey) && isset($isKeyValid) && $isKeyValid) { ?>
			<fieldset class='form-group'>
				<legend>Information</legend>
				
				<div class='row form-group'>
					<div class='col-xs-4'>
						<label for='Username'>Username</label>
					</div>
					<div class='col-xs-8'>
						<input type='text' readonly="true" id='Username' name='username' class='form-control' value='<?php echo $username ?>' />
					</div>
				</div>
				<div class='row form-group'>
					<div class='col-xs-4'>
						<label for='UserPassword'>Password</label>
					</div>
					<div class='col-xs-8'>
						<input type='password' id='UserPassword' name='password' required='required' minlength='6' maxlength='16'
							   class='form-control' value='' />
					</div>
				</div>
				<div class='row form-group'>
					<div class='col-xs-4'>
						<label for='UserConfirmPassword'>Confirm Password</label>
					</div>
					<div class='col-xs-8'>
						<input type='password' id='UserConfirmPassword' name='userConfirmPassword' required='required'
							   minlength='6' maxlength='16' class='form-control' value='' />
					</div>
				</div>
				<div class='row form-group'>
					<div class='col-xs-4'>
						<label for='UserValidationKey'>Validation Key</label>
					</div>
					<div class='col-xs-8'>
						<input type='text' id='UserValidationKey' name='userValidationKey' readonly="true"
							   required='required' class='form-control' value='<?php echo $validationKey ?>' />
					</div>
				</div>
			</fieldset>

		<?php } else { ?>
			<fieldset class='form-group'>
				<legend>Information<small>Please enter the email address you used when registering to receive further instructions</small></legend>
				<div class='row form-group'>
					<div class='col-xs-4'>
						<label for='EmailAddress'>Email Address</label>
					</div>
					<div class='col-xs-8'>
						<input type='text' id='EmailAddress' name='userEmail' value="" class='form-control' />
					</div>
				</div>
			</fieldset>

		<?php } ?>
		<div class='text-right'>
			<button class='btn btn-primary' type='submit' name='action' value='submit'>Submit</button>
		</div>
	</form>
	<script>
		$(function() {
			$("#ResetPasswordForm").validate({
				errorElement: "div",
				rules: {
					userEmail: {
						required: true,
						email:true
					},
					userConfirmPassword: {
						equalTo: "#UserPassword"
					}
				}
			});
					
			$("#ResetPasswordForm").ajaxForm({
				method:"post",
				dataType:"json",
				success:function(resp) {
					if(resp.status == 1) {
						var successDiv = $("<div />");
						successDiv.html(resp.successMessage);
						$("#ResetPasswordForm").replaceWith(successDiv);
					} else {
						alert(resp.errorMessage);
					}
				},
				error:function(resp) {
					alert("Error connecting to server.");
				}
			});
		});
	</script>
