<form id="CreateTeam" method='post' action="<?php echo $router->pathFor('team-quick-add', ['leagueID' => $curLeague->getId()] ) ?>">
    <div class="row form-group">
        <div class="col-xs-4">
            <label for="EditTeamName">New Team Name</label>
        </div>
        <div class="col-xs-8">
            <input class="form-control" type="text" id="CreateTeamName" name="teamName" value="" />
        </div>
    </div>
</form>