<?php $regSeason = end($seasonsAvailableForRegistration); ?>

<form id='EditGroupForm'>
	<input type='hidden' name='sportID' value='<?php echo $sport->getId() ?>' />
	
	<div class='row form-group'>
		<div class='col-xs-12 col-sm-3 col-sm-push-9 text-right'>
			<img src='<?php echo $sport->getLogoLink() ?>' />
		</div>
		<div class='col-xs-12 col-sm-9 col-sm-pull-3'>
			<h1>Register as Individual or Small Group</h1>
		</div>
	</div>
	<fieldset class='form-group'>
		<legend>League Information<small>Select your preferences in order of importance.</small></legend>
		<!-- <div class='row form-group'>  // Commenting this all out because it isn't necessary if they click from a sport's page. This section is to let them choose sport if they come from registration page
			<div class='col-md-2 col-sm-3 col-xs-4'>
				<label for='chosenSport'>Sport <span class="required">*</span></label>
			</div>
			<div class='col-md-10 col-sm-9 col-xs-8'>
				<select name="chosenSportID" id="chosenSport" class='form-control' required='required' method='post' onchange="document.location.href='<?//php echo $router->pathFor('dashboard-register-group', ['sportID' => $_POST['chosenSportID']] ); ?>'">
					<option value="-1">-- Sport --</option>
					<?/*php 
						foreach($sports as $curSport)
						{
							print "<option value='" . $curSport->getId() . "'>" . $curSport->getName() . "</option>";
						}

					*/?>
				</select>
			</div>
		</div> -->
		<div class='row form-group'>
			<div class='col-md-2 col-sm-3 col-xs-4'>
				<label for='GroupLeague'>Preferred League&nbsp;<span class="required">*</span></label>
			</div>
			<div class='col-md-10 col-sm-9 col-xs-8'>
					<select name="leagueID" id="GroupLeague" class='form-control' required='required'>
						<option value="-1">-- League --</option>
						<?php if(count($leaguesAvailableForRegistration) > 0) { ?>
							<optgroup label='<?php echo $leaguesAvailableForRegistration[0]->getSeason()->getName() ?> Leagues'>
								<?php 
									$lastSeasonId = 0;
									foreach($leaguesAvailableForRegistration as $curLeague) {

										if($curLeague->getSeasonId() != $lastSeasonId && $lastSeasonId != 0) {
											print '</optgroup><optgroup label="' . $curLeague->getSeason()->getName() . ' Leagues">';
										}

										print "<option value='" . $curLeague->getId() . "'>"
												. $curLeague->getRegistrationFormattedName()
												. "</option>";

										$lastSeasonId = $curLeague->getSeasonId();
									}
								?>
							</optgroup>
						<?php } ?>
					</select>
			</div>
		</div>
		<div class='row form-group'>
			<div class='col-md-2 col-sm-3 col-xs-4'>
				<label for='GroupLeague'>2nd Choice</label>
			</div>
			<div class='col-md-10 col-sm-9 col-xs-8'>
					<select name="leagueID2" id="GroupLeague" class='form-control'>
						<!-- LeagueID changed to leagueID2 to avoid required message, don't know if this screws with the parsing yet -->
						<option value="-1"></option>
						<?php if(count($leaguesAvailableForRegistration) > 0) { ?>
							<optgroup label='<?php echo $leaguesAvailableForRegistration[0]->getSeason()->getName() ?> Leagues'>
								<?php 
									$lastSeasonId = 0;
									foreach($leaguesAvailableForRegistration as $curLeague) {

										if($curLeague->getSeasonId() != $lastSeasonId && $lastSeasonId != 0) {
											print '</optgroup><optgroup label="' . $curLeague->getSeason()->getName() . ' Leagues">';
										}

										print "<option value='" . $curLeague->getId() . "'>"
												. $curLeague->getRegistrationFormattedName()
												. "</option>";

										$lastSeasonId = $curLeague->getSeasonId();
									}
								?>
							</optgroup>
						<?php } ?>
					</select>
			</div>
		</div>
		<div class='row form-group'>
			<div class='col-md-2 col-sm-3 col-xs-4'>
				<label for='GroupLeague'>3rd Choice</label>
			</div>
			<div class='col-md-10 col-sm-9 col-xs-8'>
					<select name="leagueID3" id="GroupLeague" class='form-control'>
						<option value="-1"></option>
						<?php if(count($leaguesAvailableForRegistration) > 0) { ?>
							<optgroup label='<?php echo $leaguesAvailableForRegistration[0]->getSeason()->getName() ?> Leagues'>
								<?php 
									$lastSeasonId = 0;
									foreach($leaguesAvailableForRegistration as $curLeague) {

										if($curLeague->getSeasonId() != $lastSeasonId && $lastSeasonId != 0) {
											print '</optgroup><optgroup label="' . $curLeague->getSeason()->getName() . ' Leagues">';
										}

										print "<option value='" . $curLeague->getId() . "'>"
												. $curLeague->getRegistrationFormattedName()
												. "</option>";

										$lastSeasonId = $curLeague->getSeasonId();
									}
								?>
							</optgroup>
						<?php } ?>
					</select>
			</div>
		</div>
	</fieldset>
	<fieldset class='form-group'>
		<legend>Player Information<small>First additional player will be the alternate contact for the group.</small></legend>
		<div id="RegPlayersContainer" style="height:212px;overflow:hidden;">
			<div class='table-responsive'>
				<table id="groupMembers" class="table table-condensed table-striped">
					<thead>
						<tr>
							<th></th>
							<th>First Name</th>
							<th>Last Name</th>
							<th>Email</th>
							<th>Phone Number</th>
							<th>Gender</th>
							<th>Skill Level</th>
						</tr>
					</thead>
					<tbody>
						<?php $numPlayers = (isset($sport) && $sport->getId() != null) ? $sport->getNumPlayerInputsForRegistration() : 10 ?>
						<?php for($i = 0; $i < $numPlayers; $i++) { ?>
							<?php 
								$curPlayer = new Models_Player();

								$firstName = $curPlayer->getFirstName();
								$lastName = $curPlayer->getLastName();
								$email = $curPlayer->getEmail();
								$gender = $curPlayer->getGender();
							?>
							<tr>
								<td style="min-width:45px;"><?php echo $i == 0 ? "You <span class='required'>*</span>" : $i + 1; ?>
								<td>
									<label class='sr-only' for='PlayerFirstName_<?php echo $i ?>'>First Name</label>
									<input type='text' style="min-width:50px;" class='form-control' id='PlayerFirstName_<?php echo $i ?>' name='playerFirstName_<?php echo $i ?>' value='<?php echo htmlentities($firstName, ENT_QUOTES) ?>' <?php echo $i == 0 ? "required='required'" : "" ?> />
								</td>
								<td>
									<label class='sr-only' for='PlayerLastName_<?php echo $i ?>'>Last Name</label>
									<input type='text' style="min-width:50px;" class='form-control' id='PlayerLastName_<?php echo $i ?>' name='playerLastName_<?php echo $i ?>' value='<?php echo htmlentities($lastName, ENT_QUOTES) ?>' <?php echo $i == 0 ? "required='required'" : "" ?> />
								</td>
								<td>
									<label class='sr-only' for='PlayerEmail_<?php echo $i ?>'>Email</label>
									<input type='text' style="min-width:200px;" class='form-control' id='PlayerEmail_<?php echo $i ?>' name='playerEmail_<?php echo $i ?>' value='<?php echo htmlentities($email, ENT_QUOTES) ?>' <?php echo $i == 0 ? "required='required'" : "" ?> />
								</td>
								<td>
									<?php $phoneNumber ='' // Remove this later - see skillLevel note ?>
									<label class='sr-only' for='PlayerPhoneNumber_<?php echo $i ?>'>Phone Number</label>
									<input type='text' style="min-width:100px;" class='form-control' id='PlayerPhoneNumber_<?php echo $i ?>' value='<?php echo htmlentities($phoneNumber, ENT_QUOTES) ?>' <?php echo $i == 0 ? "required='required'" : "" ?> />
								</td>
								<td>
									<label class='sr-only' for='PlayerGender_<?php echo $i ?>'>Gender</label>
									<select id='PlayerGender_<?php echo $i ?>' style="min-width:100px;" name="playerGender_<?php echo $i ?>" class='form-control'>
										<option value='M'>Male</option>
										<option value='F'>Female</option>
									</select>
								</td>
								<td>
									<label class='sr-only' for='PlayerSkill_<?php echo $i ?>'>Skill Level</label>
									<select id='PlayerSkill_<?php echo $i ?>' style="min-width:100px;" name="PlayerSkill_<?php echo $i ?>" class='form-control'>
										<option value='-1'>Choose</option>
										<option value='5'>5 (High)</option>
										<option value='4'>4</option>
										<option value='3'>3</option>
										<option value='2'>2</option>
										<option value='1'>1 (Low)</option>
									</select>
								</td>
							</tr>
						<?php } ?>
					</tbody>
				</table>
			</div>
		</div>
		<div style="border-top:1px solid #e5e5e5" class="text-center panel-body" id="RegPlayersMoreContainer">
			<button type="button" class="btn btn-primary" onclick="displayAllPlayers();">More Players <span class="glyphicon glyphicon-chevron-down"></span></button>
		</div>
	</fieldset>
	<fieldset class='form-group'>
		<legend>Comments<small>Comments, notes, player needs, etc. (limit 1000 characters).</small></legend>

		<div class='row form-group'>
			<div class='col-md-2 col-xs-4'>
				<label for='TeamComments'>Comments</label>
			</div>
			<div class='col-md-10 col-xs-8'>
				<textarea class='form-control' name="teamComments" id='TeamComments'></textarea>
			</div>
		</div>
		<div class='row form-group'>
			<div class='col-md-2 col-xs-4'>
				<label for='CapHowHeardMethod'>How did you hear about us?</label>
			</div>
			<div class='col-md-10 col-xs-8'>
				<select name="capHowHeardMethod" id='CapHowHeardMethod' class='form-control' onchange="showTextbox(this)">
					<option value="0">Choose Method</option>
					<option value="1">Google/Internet Search</option>
					<option value="2">Facebook Page</option>
					<option value="3">Kijiji Ad</option>
					<option value="4">Returning Player</option>
					<option value="5">From A Friend</option>
					<option value="6">Restaurant Advertisement</option>
					<option value="7">The Guelph Community Guide</option>
					<option value="8">Other</option>            
				</select>
			</div>
		</div>
		<div class='row form-group' id='HowHeardOtherMethod' <?php echo $team->getCaptain()->getHowHeardMethod() != 8 ? "style='display:none;'" : "" ?>>
			<div class='col-md-2 col-xs-4'>
				<label for='CapHowHeardMethodOther'>Please specify other method</label>
			</div>
			<div class='col-md-10 col-xs-8'>
				<input name="capHowHeardMethodOther" class='form-control' id='CapHowHeardMethodOther' value='<?php echo htmlentities($team->getCaptain()->getHowHeardOtherText(), ENT_QUOTES) ?>' type='text' />
			</div>
		</div>
	</fieldset>
	<fieldset id='EditGroupFeesSection' class='form-group' data-display='true'>
		<legend>Confirm Fees<small>The registration process is not finalized until fees have been paid.</small></legend>
		<div class='row form-group'>
			<div class='col-md-2 col-xs-4'>
				<label for='groupPayMethod'>Method <span class="required">*</span></label>
			</div>
			<div class='col-md-10 col-xs-8'>
				<select name="groupPaymentMethod" id='groupPayMethod' class='form-control'>
					<option value="-1" readonly='readonly'>Choose Payment Method</option>
					<option value="1">I will send an email money transfer to dave@perpetualmotion.org</option>
					<option value="2">I will mail cheque to Perpetual Motion's home office</option>
					<option value="3">I will bring cash/cheque to Perpetual Motion's home office</option>
					<?php if(!empty($regSeason) && ($regSeason->getName() == 'Spring' || $regSeason->getName() == 'Summer')) { ?>
						<option value="4">I will bring cash/cheque to registration night</option>
					<?php } ?>
				</select>
			</div>
		</div>
		<p class='text-center'><strong>Make Cheques Payable to Perpetual Motion</strong></p>
		<p class='text-center'><strong>Send This Confirmation Form & Fees to:</strong><br />78 Kathleen St. Guelph, Ontario; N1H 4Y3</p>
	</fieldset>
    <?php if(!empty($regSeason)) { ?>
        <fieldset class='registrationDate'>
            <legend>Registration Due By</legend>
            <h4><?php print $regSeason->getName() ?> League</h4>
            <?php 
                if($regSeason->getIsRegistrationBySport()) {
                    foreach($sports as $curSport) {
                        echo "<div class='row'>" 
                            . "<div class='col-xs-3'>" . $curSport->getName() . "</div>"
                            . "<div class='col-xs-9'><span class='red'><strong>" . date("F d, Y", $curSport->getRegistrationDueDate()) . "</strong></span></div>"
                        . "</div>";
                    }
                } else {
                    echo $regSeason->getRegistrationDueBy();
                }
            ?>
        </fieldset>
	<?php } ?>
    <p>&nbsp;</p>
	<fieldset class='form-group'>
			<legend>Register<small>Submit your group registration to the convenor.</small></legend>
		<p>
			<button type='submit' class='btn btn-primary' name='submit' value='register' onclick='$("#EditGroupForm input[name=action]").val("register");'>
				<span class='glyphicon glyphicon-saved'></span> Register
			</button>
			<button type='button' class="btn btn-primary pull-right" onclick='javascript:window.print();'><span class='glyphicon glyphicon-print'></span> Print Form</button>
		</p>
	</fieldset>
</form>

<script>
	$(function() {
		$.validator.addMethod("registering", 
			function(value, element) {
				if($("#EditGroupForm input[name=action]").val() === 'save') {
					return true;
				}
				
				if($("#EditGroupFeesSection").attr('data-display') === 'false') {
					return true;
				} else {
					return $(element).val() > 0;
				}
			}, "Please enter your payment method."
		);

		$("#EditGroupForm").validate({
			rules: {
				groupPaymentMethod: {
					"registering": true
				},
				leagueID: {
					required: true,
					min: 13
				}
			},
			messages: {
				leagueID: "League is required"
			},
			submitHandler:function(form) {
				var paymentSection = $("#EditGroupFeesSection");
				
				//if($("#EditGroupForm input[name=action]").val() === "register" && paymentSection.attr('data-display') === 'false') {
				//	paymentSection.attr('data-display', 'true');
				//	paymentSection.slideDown(300);
				//	return;
				//}
				
				$(form).ajaxSubmit({
					type:"post",
					url:"<?php echo $router->pathFor('save-group'); ?>",
					dataType:"json",
					success:function(resp) {
						if(resp.status === 1) {
							document.location = "<?php echo $router->pathFor('registration-success', []); ?>";
						} else {
							alert(resp.errorMessage);
						}
					},
					error:function() {
						alert("Error connecting to server");
					}
				});
			},
			invalidHandler:function(event, validator) {
				var errors = validator.numberOfInvalids();
				if (errors) {
					var message = errors == 1
						? 'You missed 1 field. It has been highlighted'
						: 'You missed ' + errors + ' fields. They have been highlighted';
					alert(message);
				}
			}
		})
	});
	
	function showTextbox(self) {
		
		if($(self).val() == 8) {
			$('#HowHeardOtherMethod').slideDown();
		} else {
			$('#HowHeardOtherMethod').slideUp();
		}
	}
	
	function displayAllPlayers() {
		//var $text = ;
		//var contentHeight = $text.addClass('heightAuto').height();
		
		$("#RegPlayersContainer").animate({ 
			height: $("#groupMembers").height()
		}, 500);
		
		$("#RegPlayersMoreContainer").slideUp();
	}
</script>
