
<h1>Search</h1>

<form action="<?php echo $router->pathFor('dashboard-search-page'); ?>" method="post" id="SearchTeamsPageForm">
	<div class="form-group row">
		<div class="col-sm-5 col-xs-4"><label for="TeamSearchString">Search</label></div>
		<div class="col-sm-7 col-xs-8">
			<input id="TeamSearchString" type="text" name="search" class="form-control" placeholder="Search" 
				   value="<?php echo htmlspecialchars($searchString, ENT_QUOTES); ?>" />
		</div>
	</div>
	<div class="form-group">
		<button type="submit" class="btn btn-primary pull-right">Submit</button>
	</div>
	<div class="clearfix"></div>
</form>

<h2>Results</h2>
	
<table id="TeamSearchData" class="table table-striped table-responsive">
	<thead>
		<tr>
			<th>Name</th>
			<th>League</th>
			<th>Season</th>
		</tr>
	</thead>
	<tbody>
		<?php /* foreach($teams as $curTeam) { ?>
			<tr>
				<td><a href="<?php echo $router->pathFor('dashboard-team-page', ['teamID' => $curTeam->getId()] ); ?>"><?php echo $curTeam->getName() ?></a></td>
				<td><?php echo $curTeam->getLeague()->getName() . ' - ' . $curTeam->getLeague()->getDayString() . ' - ' . $curTeam->getLeague()->getSport()->getName() ?></td>
				<td data-sort="<?php echo $curTeam->getDateCreated() ?>">
					<?php echo $curTeam->getLeague()->getSeason()->getName() . " " . $curTeam->getLeague()->getSeason()->getYear() ?>
				</td>
			</tr>
		<?php } */ ?>
	</tbody>
</table>
<script>
	$(function() {
		var myTable = $("#TeamSearchData").DataTable({
			"processing": true,
			"serverSide": true,
			"pageLength" : 25,
			"searching": false,
			"order": [],
			"ajax": {
				url: "<?php echo $router->pathFor('search-teams'); ?>",
				type:"post",
				data: function(d) {
					var formData = $("#SearchTeamsPageForm").serializeArray();
					var filterFormData = {};

					// Generating multimap to serialize in traditional way
					for (var i in formData) {
						var field = formData[i];
						var existing = filterFormData[field["name"]];
						if (existing) {
							existing.push(field["value"]);
							filterFormData[field["name"]] = existing;
						} else {
							filterFormData[field["name"]] = [field["value"]];
						}
					}
					// Adding filter form data, serialized in traditional way, to Datatables data, serialized in non-traditional way
					return $.param(d) + "&" + $.param(filterFormData, true);
				}
			},
			columns: [
				{ data: "teamLink" },
				{ data: "league" },
				{ data: {
					_:    "season.display",
					sort: "season.timestamp"
				} }
			]
		});

		$("#SearchTeamsPageForm").submit(function() {
			myTable.ajax.reload();
			return false;
		})
	});
</script>