<?php 
/*****************************************
File: unbalanced-standings.php
Creator: Derek Dekroon
Created: June 16/2018
Program that tells the user of any potential issues with the score submissions/standings.
******************************************/
?>

<?php 
	$numTeamsWithUnbalancedSubmissions = 0;
	$numTeamsWithUnbalancedStandings = 0;
	$numTeamsWithIncorrectNumberOfSubmissions = 0; 
?>

<h1>Unbalanced Standings</h1>
<form method='POST' action='teamStandingsViewer.php'>
	<h2>Uneven Score Submissions</h2>
	<table>
		<thead>
			<tr>
				<th>ID</th>
				<th>Team Name</th>
				<th>Captain Email</th>
				<th>League Name</th>
				<th colspan="3">Team Submission Results</th>
				<th colspan="3">Opponent Submission Results</th>
			</tr>
			<tr>
				<th colspan="4"></th>
				<th>Wins</th>
				<th>Losses</th>
				<th>Ties</th>
				<th>Wins</th>
				<th>Losses</th>
				<th>Ties</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach($teams as $curTeam) { ?>
				<?php $oppSubmittedGames = $curTeam->getOppSubmittedWins() + $curTeam->getOppSubmittedLosses() + $curTeam->getOppSubmittedTies(); ?>
				<?php $submittedGames = $curTeam->getWins() + $curTeam->getLosses() + $curTeam->getTies(); ?>
				<?php if($submittedGames == $oppSubmittedGames && ($curTeam->getOppSubmittedWins() != $curTeam->getSubmittedLosses() 
						|| $curTeam->getOppSubmittedLosses() != $curTeam->getSubmittedWins() || $curTeam->getOppSubmittedTies() != 
						$curTeam->getSubmittedTies())) {  ?>

					<?php $numTeamsWithUnbalancedSubmissions = $numTeamsWithUnbalancedSubmissions + 1; ?>
					<tr>
						<td><?php print $curTeam->getId(); ?></td>
						<td><?php print "<a target='_blank' href='/control/Search/teamPage.php?teamID=" . $curTeam->getId() . "'>" . $curTeam->getName() . "</a>"; ?></td>
						<td>
							<?php $body = "Hey, I was looking through our standings and noticed an issue with your score submissions on DATE. You submitted SCORE, while your opponent TEAM submitted SCORE. I cant be sure exactly what happened but any ideas you might have as to why this error has came up would be appreciated. Thanks,";
							print "<a target='_blank' href='mailto:" . $curTeam->getCaptain()->getEmail() . "?subject=Score Submissions Issue&body=$body'>" . $curTeam->getCaptain()->getEmail() . '</a>'; ?>
						</td>
						<td>
							<?php print "<a target='_blank' href='/control/Standings/editSubmissions.php?sportID=" . $curTeam->getLeague()->getSportId() . "&leagueID=" . $curTeam->getLeagueId() . "'>" . $curTeam->getLeague()->getFormattedName() . "</a>" ?>
						</td>
						<td class="text-right"><?php print $curTeam->getSubmittedWins() ?></td>
						<td class="text-right"><?php print $curTeam->getSubmittedLosses() ?></td>
						<td class="text-right"><?php print $curTeam->getSubmittedTies() ?></td>
						<td class="text-right"><?php print $curTeam->getOppSubmittedWins() ?></td>
						<td class="text-right"><?php print $curTeam->getOppSubmittedLosses() ?></td>
						<td class="text-right"><?php print $curTeam->getOppSubmittedTies() ?></td>
					</tr>
				<?php } ?>
			<?php } ?>
			<?php if($numTeamsWithUnbalancedSubmissions == 0) { ?>
				<tr>
					<td colspan="10" class="text-center" style="font-style:italic;">
						No teams with uneven standings
					</td>
				</tr>
			<?php } ?>
		</tbody>
	</table>
	 
	<h2>Incorrect Standings</h2>
	<table>
		<thead>
			<tr>
				<th>ID</th>
				<th>Team Name</th>
				<th>Captain Email</th>
				<th>League Name</th>
				<th colspan="3">Team Submission Results</th>
				<th colspan="3">Team Standings</th>
			</tr>
			<tr>
				<th colspan="4"></th>
				<th>Wins</th>
				<th>Losses</th>
				<th>Ties</th>
				<th>Wins</th>
				<th>Losses</th>
				<th>Ties</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach($teams as $curTeam) { ?>
				<?php $submittedGames = $curTeam->getSubmittedWins() + $curTeam->getSubmittedLosses() + $curTeam->getSubmittedTies(); ?>
				<?php $standingsTotal = $curTeam->getWins() + $curTeam->getLosses() + $curTeam->getTies(); ?>
				<?php if($submittedGames != $standingsTotal) { ?>
					<tr>
						<td><?php print $curTeam->getId(); ?></td>
						<td><?php print "<a target='_blank' href='/control/Search/teamPage.php?teamID=" . $curTeam->getId() . "'>" . $curTeam->getName() . "</a>"; ?></td>
						<td>
							<?php $body = "Hey, I was looking through our standings and noticed an issue with your score submissions on DATE. You submitted SCORE, while your opponent TEAM submitted SCORE. I cant be sure exactly what happened but any ideas you might have as to why this error has came up would be appreciated. Thanks,";
							print "<a target='_blank' href='mailto:" . $curTeam->getCaptain()->getEmail() . "?subject=Score Submissions Issue&body=$body'>" . $curTeam->getCaptain()->getEmail() . '</a>'; ?>
						</td>
						<td>
							<?php print "<a target='_blank' href='/control/Standings/editSubmissions.php?sportID=" . $curTeam->getLeague()->getSportId() . "&leagueID=" . $curTeam->getLeagueId() . "'>" . $curTeam->getLeague()->getFormattedName() . "</a>" ?>
						</td>
						<td class="text-right"><?php print $curTeam->getSubmittedWins() ?></td>
						<td class="text-right"><?php print $curTeam->getSubmittedLosses() ?></td>
						<td class="text-right"><?php print $curTeam->getSubmittedTies() ?></td>
						<td class="text-right"><?php print $curTeam->getWins() ?></td>
						<td class="text-right"><?php print $curTeam->getLosses() ?></td>
						<td class="text-right"><?php print $curTeam->getTies() ?></td>
					</tr>
					<?php $numTeamsWithUnbalancedStandings = $numTeamsWithUnbalancedStandings + 1; ?>
				<?php } ?>
			<?php } ?>
			<?php if($numTeamsWithUnbalancedStandings == 0) { ?>
				<tr>
					<td colspan="10" class="text-center" style="font-style:italic;">
						No teams with incorrect standings
					</td>
				</tr>
			<?php } ?>
		</tbody>
	</table>
	
	<h2>Incorrect Number of Score Submissions</h2>
	<table>
		<thead>
			<tr>
				<th>ID</th>
				<th>Team Name</th>
				<th>Captain Email</th>
				<th>League Name</th>
				<th>Wins</th>
				<th>Losses</th>
				<th>Ties</th>
				<th>Practices</th>
				<th>Cancels</th>
				<th>League Submissions</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach($teams as $curTeam) { ?>
				<?php $numSubmissionsExpected = $curTeam->getLeague()->getNumGamesPerMatch() * $curTeam->getLeague()->getNumMatches() * $curTeam->getLeague()->getWeekInScoreReporter(); ?>
				<?php $submittedGames = $curTeam->getSubmittedWins() + $curTeam->getSubmittedLosses() + $curTeam->getSubmittedTies(); ?>
				<?php if($submittedGames > $numSubmissionsExpected || ($submittedGames < $numSubmissionsExpected &&
					$curTeam->getMostRecentWeekSubmitted() == $curTeam->getLeague()->getWeekInScoreReporter())) { ?>
					<tr>
						<td><?php print $curTeam->getId(); ?></td>
						<td><?php print "<a target='_blank' href='/control/Search/teamPage.php?teamID=" . $curTeam->getId() . "'>" . $curTeam->getName() . "</a>"; ?></td>
						<td>
							<?php $body = "Hey, I was looking through our standings and noticed an issue with your score submissions on DATE. You submitted SCORE, while your opponent TEAM submitted SCORE. I cant be sure exactly what happened but any ideas you might have as to why this error has came up would be appreciated. Thanks,";
							print "<a target='_blank' href='mailto:" . $curTeam->getCaptain()->getEmail() . "?subject=Score Submissions Issue&body=$body'>" . $curTeam->getCaptain()->getEmail() . '</a>'; ?>
						</td>
						<td>
							<?php print "<a target='_blank' href='/control/Standings/editSubmissions.php?sportID=" . $curTeam->getLeague()->getSportId() . "&leagueID=" . $curTeam->getLeagueId() . "'>" . $curTeam->getLeague()->getFormattedName() . "</a>" ?>
						</td>
						<td class="text-right"><?php print $curTeam->getSubmittedWins() ?></td>
						<td class="text-right"><?php print $curTeam->getSubmittedLosses() ?></td>
						<td class="text-right"><?php print $curTeam->getSubmittedTies() ?></td>
						<td class="text-right"><?php print $curTeam->getSubmittedPractices() ?></td>
						<td class="text-right"><?php print $curTeam->getSubmittedCancels() ?></td>
						<td class="text-right"><?php print $numSubmissionsExpected ?></td>
					</tr>
					<?php $numTeamsWithIncorrectNumberOfSubmissions = $numTeamsWithIncorrectNumberOfSubmissions + 1; ?>
				<?php } ?>
			<?php } ?> 
			<?php if($numTeamsWithIncorrectNumberOfSubmissions == 0) { ?>
				<tr>
					<td colspan="10" class="text-center" style="font-style:italic;">
						No teams with incorrect number of score submissions
					</td>
				</tr>
			<?php } ?>
		</tbody>
	</table>
</form>
<script>
	function checkAll() {
		var field = document.getElementsByName('remove[]');
		for (i = 0; i < field.length; i++)
			field[i].checked = true;
		return false;
	}
	function uncheckAll() {
		var field = document.getElementsByName('remove[]');
		for (i = 0; i < field.length; i++)
			field[i].checked = false;
		return false;
	}

	function checkYesNo() {
		return confirm('Are you sure you want to remove these submissions?');
	}
</script>