<style>

	h1 {
		font-size: 2em;
		margin-bottom: 5%;
	}
	.btn {
		padding: 5%;
		font-size: 28px;
		/*font-weight: bold;*/
		/*border-width: 1.5px;*/
		/*border-color: #000;*/
		border-radius: 8px;
	}

	.topBtn {
		margin-bottom: 5%;
	}
</style>

<form>
	<div class='row form-group'>
		<div class='col-xs-12'>
			<h1 class='text-center'>Please select your mobile device type to be directed to relevant app store</h1>
		</div>
	</div>
	<fieldset class='row form-group'>
		<div class='container-fluid'>
			<div class='col-xs-12'>
				<a href="https://play.google.com/store/apps/details?id=com.perpetualmotion.PMotionApp">
					<button type='button' class='btn btn-primary btn-block topBtn'>Android</button>
				</a>
			</div>
			<div class='col-xs-12'>
				<a href="#">
					<button class='btn btn-primary btn-block' onclick="">iOS</button>
				</a>
			</div>
		</div>
	</fieldset>
</form>

<div class='container-fluid'>
	<div class='col-xs-12'>
		<center><img class='img-responsive' src="/Logos/Perpetualmotionlogo2.jpg"></center>
	</div>
</div>
