
	<div class='clearfix form-group'>
		<h1>My Dashboard</h1>
	</div>
	<?php if(sizeof($seasonsInScoreReporter) > 0) { ?>
		<fieldset class='form-group'>
			<legend>Active Teams</legend>
			<?php foreach($seasonsInScoreReporter as $regSeason) { ?>
				<h4 style='margin-top:0;'><?php print $regSeason->getName() . ' ' . $regSeason->getYear() ?></h4>
				<div class="row flex flex-wrap flex-stretch">
					<?php foreach(Includes_DayOfWeek::getDays() as $day) { ?>
						<?php if($day == Includes_DayOfWeek::SATURDAY || $day == Includes_DayOfWeek::FRIDAY) continue; ?>
						<?php $myTeams = $teamsController->getTeamsForUser($user, $regSeason, $day); ?>
						<div class="<?php if($day == Includes_DayOfWeek::WEDNESDAY) echo "col-sm-offset-2"; ?> col-sm-4 col-xs-6">
							<div class="panel <?php echo $day == date('N') % 7 ? 'panel-primary' : 'panel-default' ?>" style="padding:0;">
								<div class="panel-heading text-center f-small">
									<?php echo Includes_DayOfWeek::getDayString($day); ?>
								</div>
								
								<?php if(sizeof($myTeams) > 0) { ?>
									<?php foreach($myTeams as $curDayTeam) { ?>
										<div class="panel-body text-center">
											<div><img style='max-height:50px;' src='<?php echo $curDayTeam->getLeague()->getSport()->getLogoLink() ?>' title='' /></div>
											<strong><?php echo $curDayTeam->getName() ?></strong>
										</div>
									<?php } ?>
								<?php } else { ?>
									<div class="panel-body text-center">
										<i><small>No Teams</small></i> 
									</div>
								<?php } ?>
							</div>
						</div>
					<?php } ?>
				</div>
			<?php } ?>
		</fieldset>
	<?php } ?>
	<?php if(sizeof($seasonsInRegistration) > 0) { ?>
		<fieldset class='form-group'>
			<legend>Future Teams</legend>
			<?php foreach($seasonsInRegistration as $regSeason) { ?>
				<?php if($regSeason->getIsAvailableScoreReporter()) continue; ?>
				<h4 style='margin-top:0;'><?php print $regSeason->getName() . ' ' . $regSeason->getYear() ?></h4>
					<div class="row flex flex-wrap flex-stretch">
					<?php foreach(Includes_DayOfWeek::getDays() as $day) { ?>
						<?php if($day == Includes_DayOfWeek::SATURDAY || $day == Includes_DayOfWeek::FRIDAY) continue; ?>
						<?php $myTeams = $teamsController->getTeamsForUser($user, $regSeason, $day); ?>
						<div class="<?php if($day == Includes_DayOfWeek::WEDNESDAY) echo "col-sm-offset-2"; ?> col-sm-4 col-xs-6">
							<div class="panel panel-default" style="padding:0;">
								<div class="panel-heading text-center f-small">
									<?php echo Includes_DayOfWeek::getDayString($day); ?>
								</div>
								
								<?php if(sizeof($myTeams) > 0) { ?>
									<?php foreach($myTeams as $curDayTeam) { ?>
										<div class="panel-body text-center">
											<div><img style='max-height:50px;' src='<?php echo $curDayTeam->getLeague()->getSport()->getLogoLink() ?>' title='' /></div>
											<strong><?php echo $curDayTeam->getName() ?></strong>
										</div>
									<?php } ?>
								<?php } else { ?>
									<div class="panel-body text-center">
										<i><small>No Teams</small></i> 
									</div>
								<?php } ?>
							</div>
						</div>
					<?php } ?>
				</div>
			<?php } ?>
		</fieldset>
	<?php } ?>
	<fieldset id='MatchesFieldset' class='form-group visible-sm visible-md visible-lg'>
		<legend>Past Teams</legend>
		<table id="PastTeamsTable" class="table table-condensed table-striped table-hover table-responsive">
			<thead>
				<tr>
					<th>Name</th>
					<th>League</th>
					<th>Season</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				<?php foreach($user->getTeams() as $curTeam) { ?>
					<?php if($curTeam->getLeague() != null && $curTeam->getLeague()->getSeason() != null &&
							(!$curTeam->getLeague()->getSeason()->getIsAvailableRegistration() && !$curTeam->getLeague()->getSeason()->getIsAvailableScoreReporter())) { ?>
						<tr>
							<td>
								<?php //TODO link to edit or view page. <a href="<?php echo $router->pathFor('edit-team', ['teamID' => $curTeam->getId()] ); "><?php echo $curTeam->getName() </a> ?>
								<?php echo $curTeam->getName() ?>
							</td>
							<td><?php echo $curTeam->getLeague()->getId() !== null ? $curTeam->getLeague()->getName() . ' - ' . $curTeam->getLeague()->getDayString() . ' - ' . $curTeam->getLeague()->getSport()->getName() : "" ?></td>
							<td data-sort="<?php echo $curTeam->getDateCreated() ?>">
								<?php echo $curTeam->getLeague()->getId() !== null ? $curTeam->getLeague()->getSeason()->getName() . " " . $curTeam->getLeague()->getSeason()->getYear() : "" ?>
							</td>
							<td>
								<?php if($curTeam->getLeague()->getId() !== null) { ?>
									<div class='btn-group btn-group-sm float-right'>
										<a class='btn btn-primary' href="<?php echo $router->pathFor('dashboard-team-page', ['teamID' => $curTeam->getId()] ); ?>">
											<span class='glyphicon glyphicon-picture'></span> Team Page
										</a>
									</div>
								<?php } ?>
							</td>
						</tr>
					<?php } ?>
				<?php } ?>
			</tbody>
		</table>
	</fieldset>
	<script>
		$(function() {
			$("#PastTeamsTable").DataTable({
				"columns": [
					{ "orderable": false },
					{ "orderable": false },
					{ "orderable": false },
					{ "orderable": false }
				],
				"order": [[ 2, "desc" ]]
			});
		});
	</script>
