
	<link href="/css/stylesheets/jquery-ui.min.css" rel="stylesheet" type="text/css" />
	<link href="/css/stylesheets/styles.css" rel="stylesheet" type="text/css" />
	
	<h1><?php print $team->getName() ?> - <?php print $team->getLeague()->getName() ?> - <?php print $team->getLeague()->getDayString() ?></h2>
	<p class='teamStandings f-large'><?php print $team->getFormattedStandings(); ?></p>

	<div class="matchInfo" align="center">
		<?php $rowNum = 0; ?>
		<table class="table table-condensed table-striped table-responsive f-small">
			<thead>
				<tr>
					<th></th>
					<th>Date</th>
					<th>Opponent</th>
					<th>Result</th>
					<th>Field</th>
					<th>Game Time</th>
					<?php if($team->getLeague()->getSportId() != 2) { ?>
						<th>Colour</th>
					<?php } ?>
				</tr>
			</thead>
			<tbody>
				<?php if($team->getScheduledMatches() != null) { ?>
					<?php $matchCount = 0; ?>
					<?php $lastTeamId = 0; ?>
					<?php foreach($team->getScheduledMatches() as $scheduledMatch) { ?>
						<?php $teamScoreSubmissions = $scheduledMatch->getScoreSubmissions($team); ?>
						<tr>
							<td><?php print ++$matchCount ?></td>
							<td><?php print $scheduledMatch->getFormattedDatePlayed(); ?></td>
							<td>
								<?php if(($teamScoreSubmissions != null && sizeof($teamScoreSubmissions) > 0)) { ?>
									<?php foreach($teamScoreSubmissions as $scoreSubmission) { ?>
										<?php if($scoreSubmission->getOppTeam()->getId() != $lastTeamId) { ?>
											<?php $lastTeamId = $scoreSubmission->getOppTeam()->getId(); ?>
								
											<?php if ($scoreSubmission->getOppTeam()->getId() != 1 && !$scoreSubmission->getOppTeam()->getIsDroppedOut()) { ?>
												<?php $teamPageUrl = $isDashboard ? $router->pathFor('dashboard-team-page', ['teamID' => $scoreSubmission->getOppTeam()->getId()] ) : $router->pathFor('team-page', ['teamID' => $scoreSubmission->getOppTeam()->getId()] ) ?>
												<a href='<?php echo $teamPageUrl ?>'><?php print $scoreSubmission->getOppTeam()->getName() ?></a>
												<?php print $scoreSubmission->getOppTeam()->getFormattedStandings(); ?>
											<?php } else { ?>
												<?php print $scoreSubmission->getOppTeam()->getName(); ?>
											<?php } ?>
												
											<?php break; ?>
										<?php } ?>
									<?php } ?>
								<?php } else { ?>
									<?php if ($scheduledMatch->getOppTeam($team)->getId() != 1 && !$scheduledMatch->getOppTeam($team)->getIsDroppedOut()) { ?>
										<?php $teamPageUrl = $isDashboard ? $router->pathFor('dashboard-team-page', ['teamID' => $scheduledMatch->getOppTeam($team)->getId()] ) : $router->pathFor('team-page', ['teamID' => $scheduledMatch->getOppTeam($team)->getId()] ) ?>
										<a href='<?php echo $teamPageUrl ?>'><?php print $scheduledMatch->getOppTeam($team)->getName() ?></a>
										<?php print $scheduledMatch->getOppTeam($team)->getFormattedStandings(); ?>
									<?php } else { ?>
										<?php print $scheduledMatch->getOppTeam($team)->getName(); ?>
									<?php } ?>
								<?php } ?>
							</td>
							<td>
								<?php if($teamScoreSubmissions != null && sizeof($teamScoreSubmissions) > 0) {
									$first = true;
									foreach($teamScoreSubmissions as $scoreSubmission) {
										if($scoreSubmission->getOppTeam()->getId() == $lastTeamId) {
											print (!$first ? ", " : "") . $scoreSubmission->getResultsString();
											$first = false;
										}
									}
								} ?>
							</td>
							<td>
								<a target='_blank' href='http://www.perpetualmotion.org<?php echo $scheduledMatch->getVenue()->getLink() ?>'>
									<?php echo $scheduledMatch->getVenue()->getShortShowName() ?>
								</a>
							</td>
							<td><?php print $scheduledMatch->getFormattedGameTime() ?></td>
							<?php if($team->getLeague()->getSportId() != 2) { ?>
								<td id='shirtColour'><?php echo $scheduledMatch->getTeamOneId() == $team->getId() ? "Dark" : "Light" ?></td>
							<?php } ?>
						</tr>
					<?php } ?>
				<?php } ?>
			</tbody>
		</table>
	</div>
	<p>** For playoffs please see the <a target='_top' href='http://perpetualmotion.org/<?php echo $team->getLeague()->getSport()->getBaseUrl() ?>/<?php echo $team->getLeague()->getSport()->getBaseUrl() ?>-schedule?leagueID=<?php echo $team->getLeague()->getId() ?>'>full schedule</a></p>
	
	<p>&nbsp;</p>
	
	<?php if($team->getIsPic()) { ?>
	
		<div class='text-center'>
			<img src="<?php print $team->getPic() ?>" style="max-width:576px;" />
		</div>
		<p>&nbsp;</p>
		
	<?php } ?>
		
	<?php 
		if($isDashboard) {
			print $this->fetch('standings.phtml', [
				"router" => $router,
				"request" => $request,
				"user" => $user,
				"league" => $team->getLeague(),
				"leagueController" => $leagueController,
				"teamController" => $teamController,
				"includedInTeamPage" => true,
				"isDashboard" => true
			]); 
		} else {
			print $this->fetch('standings.phtml', [
				"router" => $router,
				"request" => $request,
				"league" => $team->getLeague(),
				"leagueController" => $leagueController,
				"teamController" => $teamController,
				"includedInTeamPage" => true,
				"isDashboard" => false
			]); 
		}
	?>
