
	<div class='clearfix form-group'>
		<h1>Registration</h1>
	</div>

	<fieldset id='MatchesFieldset' class='form-group'>
		<legend>
			Previous Teams Registered
			<small>Click on your team's name to re-register a previous team for the <?php print $regSeason->getName() ?> league</small>
		</legend>

		<?php if($regSeason->getName() == 'Summer') { ?>
			<div class="alert alert-info" role="alert">Spring teams have first priority for summer, but must confirm registration by: <?php echo date("F d", $regSeason->getConfirmationDueBy()) ?></div>
		<?php } ?>

		<div class='table-responsive'>
			<table id="PastTeamsTable" class="table table-condensed table-striped table-hover">
				<thead>
					<tr>
						<th>Team Name</th>
						<th>League</th>
						<th>Season</th>
						<th class='visible-lg visible-md visible-sm'>Registered</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					<?php foreach($user->getTeams() as $curTeam) { ?>
						<tr>
							<td><a href="<?php echo $router->pathFor('dashboard-register-team', ['sportID' => $curTeam->getLeague()->getSportId(), 'pastTeamID' => $curTeam->getId()] ); ?>"><?php echo $curTeam->getName() ?></a></td>
							<td><?php echo $curTeam->getLeague()->getName() . " - " . $curTeam->getLeague()->getDayString() . ' - ' . $curTeam->getLeague()->getSport()->getName() ?></td>
							<td data-sort="<?php echo $curTeam->getDateCreated() ?>">
								<?php echo $curTeam->getLeague()->getSeason()->getName() . " " . $curTeam->getLeague()->getSeason()->getYear() ?>
							</td>
							<td class='visible-lg visible-md visible-sm'><?php echo $curTeam->getIsFinalized() ? "Yes" : "No" ?></td>
							<td class="text-right">
								<div class="btn-group">
									<button type="button" class="btn btn-default btn-xs dropdown-toggle" style="line-height:1;" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
										<span class="sr-only">Actions </span><span class="glyphicon glyphicon-option-horizontal"></span>
									</button>
									<ul class="dropdown-menu dropdown-menu-right">
										<li>
											<a href="<?php echo $router->pathFor('edit-team', ['teamID' => $curTeam->getId()] ); ?>">View Past Team</a>
										</li>
										<li>
											<a onclick="return false" title="Remove this team from your list of past and active teams. This cannot be undone.">
												<span class="glyphicon glyphicon-remove-sign"></span> Remove
											</a>
										</li>
									</ul>
								</div>
							</td>
						</tr>
					<?php } ?>
				</tbody>
			</table>
		</div>
	</fieldset>

	<fieldset class='registrationDate'>
		<legend>Registration Due By</legend>
		<?php 
			if($regSeason->getIsRegistrationBySport()) { 
				$regSportsByDate = array();
				
				foreach($sports as $sport) {
					
					if(!isset($regSportsByDate[$sport->getRegistrationDueDate()])) {
						$regSportsByDate[$sport->getRegistrationDueDate()] = array();
					}	
					
					$regSportsByDate[$sport->getRegistrationDueDate()][] = $sport->getName();
				}
				
				foreach($regSportsByDate as $date => $sports) {
					print "<p>" . join(", ", $sports) . ": <span class='red'><strong>" . date("F d", $date) . "</strong></span></p>";
				}
			} else {
				echo $regSeason->getRegistrationDueBy();
			}
		?>
		<p>&nbsp;</p>
	</fieldset>
	<fieldset class='bottomButtons'>
		<legend>
			Register a New Team
			<small>Select a league logo below to start a new registration</small>
		</legend>
		<div class="row logosTable">
			<div class="col-sm-3 col-xs-6">
				<a href='<?php echo $router->pathFor('dashboard-register-team', ['sportID' => 1] ); ?>'>
					<div class="sport-panel sport-panel-1 square square-75">
						<div class='position-center'>
							<img src='/Logos/ultimate_0.png' />
						</div>
					</div>
				</a>
			</div>
			<div class="col-sm-3 col-xs-6">
				<a href='<?php echo $router->pathFor('dashboard-register-team', ['sportID' => 2] ); ?>'>
					<div class="sport-panel sport-panel-2 square square-75">
						<div class='position-center'>
							<img src='/Logos/volleyball_0.png' />
						</div>
					</div>
				</a>
			</div>
			<div class="col-sm-3 col-xs-6">
				<a href='<?php echo $router->pathFor('dashboard-register-team', ['sportID' => 3] ); ?>'>
					<div class="sport-panel sport-panel-3 square square-75">
						<div class='position-center'>
							<img src='/Logos/football_0.png' />
						</div>
					</div>
				</a>
			</div>
			<div class="col-sm-3 col-xs-6">
				<a href='<?php echo $router->pathFor('dashboard-register-team', ['sportID' => 4] ); ?>'>
					<div class="sport-panel sport-panel-4 square square-75">
						<div class='position-center'>
							<img src='/Logos/soccer_0.png'>
						</div>
					</div>
				</a>
			</div>
		</div>
	</fieldset>
	
	<script>
		$(function() {
			$("#PastTeamsTable").DataTable({
				"columns": [
					{ "orderable": true },
					{ "orderable": true },
					{ "orderable": true },
					{ "orderable": true },
					{ "orderable": false }
				],
				"order": [[ 2, "desc" ]]
			});
		});
	</script>
