<?php
	$userId = !is_null($user) ? $user->getId() : '';
	$username = !is_null($user) ? $user->getUsername() : '';
	$firstName = !is_null($user) ? $user->getFirstName() : '';
	$lastName = !is_null($user) ? $user->getLastName() : '';
?>

<!DOCTYPE HTML>
<html>
    <head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    	<title>Control Panel - Perpetual Motion</title>
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		
		<?php print $this->fetch('template/header-includes.phtml', [
			"router" => $router,
			"request" => $request
		]); ?>
    </head>
    <body id="ControlPanel">
		<header class="controlPanelHeader">
			<div class="col-xs-6">
				Project: <strong>PMotion Control Panel</strong>
			</div>
			<div class="col-xs-6 text-right">
				User: <strong><a href="<?php echo $router->pathFor('control-panel', [] ); ?>"><?php echo $username ?></a></strong>
				<strong style="margin-left:20px;"><a href="/Login/logout.php?siteDirect=control" id="logout">Log out</a></strong>
			</div>
		</header>
		<main class='control-panel'>
			<div id="cols">
				<div id="aside">
					<div class="block">
						<div class="logo">
							<a href="http://www.perpetualmotion.org" target="_blank">
								<img src="/Logos/Perpetualmotionlogo2.jpg" width="200" alt="Go to the Perpetual Motion website" />
							</a>
						</div>
					</div>
					<div class="block">
						<form action="/control/Search/results.php" method="post" class="searchForm">
							<div class="searchContainer">
								<input type="text" id='searchBox' name="searchString" class="input-text" />
								<button type="submit" value="search" class="input-submit-02"><span class="glyphicon glyphicon-search"></span></button>
							</div>
							<a class="toggleSearchOptions" href="javascript:toggle('search-options');"><span class="glyphicon glyphicon-filter"></span> Search Options</a>
							<div id="search-options" style="display:none;">
								<div>
									<input id="SearchTypeActive" type="radio" name="searchType" value=1 checked="checked" />
									<label for="SearchTypeActive">Active</label>
								</div>
								<div>
									<input id="SearchTypeOldData" type="radio" name="searchType" value=2 />
									<label for="SearchTypeOldData">Old Data</label>
								</div>
								<div>
									<input id="SearchTypeFaq" type="radio" name="searchType" value=3 />
									<label for="SearchTypeFaq">FAQ</label>
								</div>
								<div>
									<a href='/control/Search/createFAQ.php'>Create FAQ</a>
								</div>
							</div>
						</form>
					</div>
					<div class="block">
						<div class="menu">
							<ul>
								<li class="has-sub"><a href="<?php echo $router->pathFor("cp-registration"); ?>">New Control Panel</a>
									<ul>
										<li class="last"><a href="<?php echo $router->pathFor("cp-registration"); ?>">Registration Control Panel</a></li>
										<li class="last"><a href="<?php echo $router->pathFor("cp-unbalanced-standings"); ?>">Unbalanced Standings</a></li>
									</ul>
								</li>
								<li class="has-sub"><a href="/control/Registration/editByLeague.php">Registration</a>
									<ul>
										<li class="last"><a href="/control/Registration/editByLeague.php">Registration Control Panel</a></li>
										<li class="last"><a href="/control/Registration/printForm.php">Printable Registration Forms (For Registration Night)</a></li>
										<li class="last"><a href="/control/Registration/editTeamCaptains.php">Edit Teams with no Captain</a></li>
									</ul>
								</li>
								<li class="has-sub"><a href="/control/Standings/unbalancedStandings.php">Standings</a>
									<ul>
										<li class="last"><a href="/control/Standings/unbalancedStandings.php">Unbalanced Standings</a></li>
										<li class="last"><a href="/control/Standings/editSubmissions.php">Edit Score Submissions</a></li>
										<li class="last"><a href="/control/Standings/closeLeagueWeek.php">Close Standings for a League Week</a></li>
										<li class="last"><a href="/control/Standings/tieBreak.php">Tie Breaker</a></li>
										<li class="last"><a href="/control/Standings/addScore.php">Create a Phantom Score</a></li>
										<li class="last"><a href="/control/Standings/cancelLeagueNight.php">Cancel a Week (Rainout)</a></li>
										<li class="last"><a href="/control/Standings/turnOnCancelOption.php">Turn on cancel option (Storm During Game)</a></li>
										<li class="last"><a href="/control/Standings/finalizeLeague.php">Finalize League Standings (End of Season)</a></li>
										<li class="last"><a href="/control/Standings/printFinalStandings.php">Print Final Standings (Awards Night)</a></li>
									</ul>
								</li>
								<li class="has-sub"><a href="/control/Leagues/leaguesControlPanel.php">Leagues & Teams</a>
									<ul>
										<li class="last"><a href="/control/Leagues/leaguesControlPanel.php">Leagues Control Panel</a></li>
										<li class="last"><a href="/control/Teams/spiritControlPanel.php">Spirit Control Panel</a></li>
										<li class="last"><a href="/control/Leagues/storeScheduleData.php">Load a Schedule into the Database</a></li>
										<li class="last"><a href="/control/Leagues/splitLeague.php">Split a League</a></li>
										<li class="last"><a href="/control/Teams/showTeamIDs.php">Team Picture ID's</a></li>
										<li class="last"><a href="/control/Teams/prizeWinners.php">Prizes Control Panel</a></li>
										<li class="last"><a href="/control/Leagues/sendLateEmail.php">Manually Send Late Emails</a></li>
										<li class="last"><a target="_blank" href="/control/Teams/showAllTeams.php">Show All Teams (Captains Meeting List)</a></li>
										<li class="last"><a href="/control/Teams/editTeam.php">Edit Teams</a></li>
									</ul>
								</li>
								<li class="has-sub"><a href="/control/Players/makeReceipt.php">Players</a>
									<ul>
										<li class="last"><a href="/control/Players/makeReceipt.php">Make a Receipt</a></li>
										<li class="last"><a href="/control/Players/addAgent.php">Add A Free Agent</a></li>
										<li class="last"><a href="/control/Players/addAgentGroup.php">Add A Small Group</a></li>
										<li class="last"><a href="/control/Players/updatePlayer.php">Edit a Player</a></li>
										<li class="last"><a href="/control/Players/showHeard.php">How Players Found Us</a></li>
										<li class="last"><a href="/control/Players/removeLateEmail.php">Cancel Team Late Email</a></li>
									</ul>
								</li>
								<li class="has-sub"><a href="/control/Email/emailCaptains.php">Email</a>
									<ul>
										<li class="last"><a href="/control/Email/emailCaptains.php">Email Captains</a></li>
										<li class="last"><a href="/control/Email/emailTeams.php">Email Teams</a></li>
										<li class="last"><a href="/control/Email/emailPlayers.php">Email Players</a></li> 
										<!-- <li class="last"><a href="/control/Email/emailContainer.php?emailTarget=4">Email Free Agents</a></li> -->
										<li class="last"><a href="/control/Email/emailPastTournaments.php">Email Past Tournament Captains</a></li>
										<li class="last"><a href="/control/Email/recentSentEmails.php">Check Sent Emails</a></li>
										<li class="last"><a href="/control/Email/addToMailList.php">Add To Mailing List</a></li>
										<li class="last"><a href="/control/Email/deleteEmails.php">Unsubscribe Emails</a></li>
									</ul>
								</li>
								<li class="has-sub"><a href="/control/Tournaments/editByLeague.php">Tournaments</a>
									<ul>
										<li class="last"><a href="/control/Tournaments/editByLeague.php">Tournament Control Panel</a></li>
										<li class="last"><a href="/control/Tournaments/submitTournament.php">Create/Edit Tournament Parameters</a></li>
										<li class="last"><a href="/control/Email/emailPastTournaments.php">Email Past Tournament Captains</a></li>
										<!--<li class="last"><a href="/control/Tournaments/editTeam.php">Edit a Team</a></li>
										<li class="last"><a href="/control/Tournaments/editPlayer.php">Edit a Player</a></li> -->
										<li class="last"><a href="/control/Tournaments/showHeard.php">How Players Found Us</a></li>
									</ul>
								</li>
								<li class="has-sub"><a href="/control/Stats/teamStats.php">Stats</a>
									<ul>
										<li class="last"><a href="/control/Stats/teamStats.php">Teams Stats Page</a></li>
										<li class="last"><a href="/control/Stats/tournamentStats.php">Tournament Stats Page</a></li>
										<li class="last"><a href="/control/Players/showHeard.php">How Players Found Us</a></li>
										<li class="last"><a href="/control/Tournaments/showHeard.php">How Tournament Players Found Us</a></li>
										<li class="last"><a href="/control/Stats/viewPolls.php">View Poll Stats</a></li>

									</ul>
								</li>
							</ul>
						</div>
					</div>
				</div>
				<!-- /aside -->
				
				<div id="content">
