				</div>
			</div>
			<!-- /cols -->
			<hr class="noscreen" />
		</main>
		<footer class="mainFooter">
			<div class="container-fluid">
				<small>&copy; Copyright <?php echo date("Y"); ?>, Perpetual Motion</small>
			</div>
		</footer>
		<?php print $this->fetch('template/footer-includes.phtml'); ?>
		<script src="/js/dashboard.js"></script>
		<script src="/js/control-panel.js"></script>
		<script src="/js/control-panel/teams.js"></script>
		<script src="/js/control-panel/players.js"></script>
    </body>
</html>
