<?php
	$userId = !is_null($user) ? $user->getId() : '';
	$username = !is_null($user) ? $user->getUsername() : '';
	$firstName = !is_null($user) ? $user->getFirstName() : '';
	$lastName = !is_null($user) ? $user->getLastName() : '';
?>

<!DOCTYPE HTML>
<html>
    <head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    	<title>Dashboard - Perpetual Motion</title>
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		
		<?php print $this->fetch('template/header-includes.phtml', [
			"router" => $router,
			"request" => $request
		]); ?>
    </head>
    <body id="Dashboard">
		<?php print $this->fetch('template/header-pixel.phtml'); ?>
		<header class="mainHeader clearfix">
			<nav class="navbar navbar-default">
				<div class="container-fluid">
					<!-- Brand and toggle get grouped for better mobile display -->
					<div class="navbar-header">
						<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
							<span class="sr-only">Toggle navigation</span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
						<a class="navbar-brand" title="Go to the Perpetual Motion website" href="http://www.perpetualmotion.org" target="_blank">
							<img src="/Logos/Perpetualmotionlogo2.jpg" width="200" />
						</a>
					</div>

					<!-- Collect the nav links, forms, and other content for toggling -->
					<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
						<ul class="nav navbar-nav">
							<!-- <?php // if($user->getAccess() == Includes_Accesslevel::ADMIN) { ?> (Kyle: commenting out so I can view tab)--> 
								<li <?php echo isset($isHomepage) && $isHomepage == true ? "class='active'" : "" ?>><a href="<?php echo $router->pathFor('dashboard' ); ?>">My Dashboard <span class="sr-only">(current)</span></a></li>
							<!-- <?php //} ?> -->
							<li <?php echo isset($isRegistration) && $isRegistration == true ? "class='active'" : "" ?>><a href="<?php echo $router->pathFor('dashboard-registration' ); ?>">Registration</a></li>
							
							<?php if($user->getAccess() == Includes_Accesslevel::ADMIN) { ?>
								<li class="dropdown visible-sm visible-md visible-lg">
									<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-search"></span> Search</a>
									<ul class="dropdown-menu">
										<li>
											<form class="navbar-form navbar-left" action="<?php echo $router->pathFor('dashboard-search-page'); ?>" method="get">
												<div class="alert alert-info f-small" role="alert">
													<span class="glyphicon glyphicon-info-sign"></span>
													Search our database for past teams. <br />This section only exists for admins (for now).
												</div>
												<div class="form-group">
													<input type="text" name="search" class="form-control" placeholder="Search">
												</div>
												<button type="submit" class="btn btn-default">Submit</button>
											</form>
										</li>
									</ul>
								</li>
							<?php } ?>
						</ul>
						<form class="navbar-form navbar-left visible-xs">
							<div class="form-group">
								<input type="text" class="form-control" placeholder="Search">
							</div>
							<button type="submit" class="btn btn-default">Submit</button>
						</form>


						<div class="userAdmin clearfix">
							<div class="avatarContainer">
								<span class="glyphicon glyphicon-user"></span>
							</div>
							<div class="pull-right">
								<div class="username">
									<?= $firstName ?> <?= $lastName ?>
								</div>
								<div class="links">
									<a class="profile" href="<?= $router->pathFor('edit-profile') ?>"><span class="glyphicon glyphicon-edit"></span> My Profile</a>
									<span class="divider">|</span> 
									<a href="<?= $router->pathFor('logout') ?>"><span class="glyphicon glyphicon-lock"></span> Logout</a>
								</div>
							</div>
						</div>
					</div><!-- /.navbar-collapse -->
				</div><!-- /.container-fluid -->
			</nav>
		</header>
		<main class='dashboard container-fluid'>
			<?php if(!$isHomepage) { ?>
				<?php //<a onclick="window.history.back();"><span class="glyphicon glyphicon-chevron-left"></span> Back</a> This thing's a good idea but in practice it sucks. ?>
			<?php } ?>
