
<script src='/js/bootstrap-form-buttonset.js'></script>
<script src='/js/bootstrap-slider.min.js'></script>
<script src='/js/bootstrap-notify.min.js'></script>

<script src='/js/jquery.form.js'></script>
<script src="/js/jquery.mask.min.js"></script>
<script src="/js/jquery.validate.min.js"></script>
<script src="/js/additional-methods.min.js"></script>
<script src="/js/jquery-ui.min.js"></script>
<script src='/css/javascripts/bootstrap.min.js'></script>
<script src="/js/datatables.min.js"></script>
<script src="/js/custom-validation-methods.js"></script>

<script src="/js/global.js"></script>
